### ISSUE TITLE
Restore favicon?

### ISSUE THREAD

**Issue by CLBarajas** [WRNS/wrns.github.io#14]
We had a custom favicon created/added to the old site in f4263066d8c3edd6a14ff05cd9740b814926231e, which got lost in the transition to the new site. Unfortunately I'm not fully parsing this documentation:

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons

If we're good to just drop in the `.png`, great, but I'm not convinced that's the path forward based on the different formats and locations specified in the docs.

**Comment by Typhos** [comment]
I intentionally removed the old favicon. The old favicon and the new favicon have significant differences that impact their suitability for use as a favicon:

### Size:
- **Old Favicon:** The dimensions are 756x756 pixels. This is much larger than the typical favicon size.
- **New Favicon:** The dimensions are 48x48 pixels, which is more appropriate for a favicon and standard for modern browsers.

### Format:
- **Old Favicon:** It is in PNG format, which is not the ideal format for favicons. Browsers typically expect .ico files for favicons because they support multiple resolutions in one file.
- **New Favicon:** It is in ICO format, which is the standard format for favicons. It allows multiple sizes and resolutions to be stored in a single file.

### Complexity:
- **Old Favicon:** The image contains detailed silhouettes and musical notes, which may look unclear or cluttered when scaled down to favicon size (16x16 or 32x32 pixels).
- **New Favicon:** Much simpler and has high contrast, so it will be more recognizable and visually appealing at typical favicon sizes.

**Comment by CLBarajas** [comment]
OK – I just don't see that "W" specifically reflected as part of the visual design of the site or WRNS brand. It would probably be better to match up against the green theme or black/white with a typewriter-style typeface.

**Comment by Typhos** [comment]
That's true, the icon was added back when the site was more  of a violet. I can update the coloration to be green and I'll swap the font to use Rubik, which is the Google-font used for the body text of the site.

**Comment by Typhos** [comment]
Update the favicon and added a manifest file to the app while I was at it.
